version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"  # پورت 6379 را expose کنید
    networks:
      - my-network #شبکه اختصاصی

networks:
  my-network:
    driver: bridge